### ISSUE TITLE
bytes is also supported

### ISSUE THREAD

**Issue by ifduyue** [litements/litequeue#13]
Hello,

https://github.com/litements/litequeue/blob/90e9694d3f9dff6db2beebeb6ba3d3dc1a3a23a0/litequeue.py#L278

Annotation is str, but bytes works, maybe change annotation to str|bytes?

```python
In [1]: from litequeue import LiteQueue

In [2]: q = LiteQueue(memory=True)

In [3]: q.put('a')
Out[3]: Message(data='a', message_id='0667127d-c488-75f4-8000-9b1e8b8dbb25', status=<MessageStatus.READY: 0>, in_time=1718691804283328000, lock_time=None, done_time=None)

In [4]: q.put(b'a')
Out[4]: Message(data=b'a', message_id='0667127e-00ab-7d4c-8000-47674cc35d04', status=<MessageStatus.READY: 0>, in_time=1718691808041979000, lock_time=None, done_time=None)

In [5]: q.pop()
Out[5]: Message(data='a', message_id='0667127d-c488-75f4-8000-9b1e8b8dbb25', status=1, in_time=1718691804283328000, lock_time=1718691813868331000, done_time=None)

In [6]: q.pop()
Out[6]: Message(data=b'a', message_id='0667127e-00ab-7d4c-8000-47674cc35d04', status=1, in_time=1718691808041979000, lock_time=1718691814732661000, done_time=None)

In [7]: q.pop()
```

**Comment by polyrand** [comment]
Hi, sorry for the late reply.

Yes, technically it can accept bytes, the same way that SQLite will accept a `BLOB` instead of a `TEXT` when inserting the data. I kept it as `str` so that it was consistent with the DB schema and the definition of `class Message:`. In retrospect, maybe it would be better to just use `bytes` / `BLOB` as the message data.
