### ISSUE TITLE
More Queues in one DB

### ISSUE THREAD

**Issue by nische** [litements/litequeue#7]
Is it possible to handle more Queues in on db by adding a Tablename?

BR, NiSche

**Comment by polyrand** [comment]
Yeah, this is something I've wanted to implement. Ideally, having one database per queue allows for better throughput and easier management overall. But in the next version I'll add an option to define the table name when initializing the class so that there can be multiple queues in the same database.

**Comment by polyrand** [comment]
I've implemented this feature. I'll publish the changes when I finish writing some tests.

**Comment by polyrand** [comment]
I couldn't get all the tests working as I wanted, I don't think it's because the feature doesn't work, but I probably won't have time to properly write them.

I have added [the queue_name](https://github.com/litements/litequeue/blob/d3837b8194d5b7e0ee18c80b391a60179c006eab/litequeue.py#L157) initialization argument, which should allow having multiple queues in one DB, although I recommend sticking to 1 SQLite file per queue unless you really need everything in the same file. I will push a new version in the next few hours so that this feature is available when installing through PyPi.

**Comment by polyrand** [comment]
This should be working with the latest version 0.8. Example usage:

```python
import tempfile

import litequeue

print(f"Pkg version: {litequeue.__version__}")


with tempfile.TemporaryDirectory() as tmpdirname:

    db_path = tmpdirname + "/test.sqlite3"

    q1 = litequeue.LiteQueue(db_path, queue_name="q1")
    q2 = litequeue.LiteQueue(db_path, queue_name="q2")

    q1.put("a")
    q1.put("b")

    print("Q1 size", q1.qsize())

    print("Q2 size", q2.qsize())

    q2.put("c")
    q2.put("d")

    print("Q2 size", q2.qsize())

    print(q1.pop())
    print(q1.peek())

    print(q2.peek())
    print(q2.pop())
```

**Comment by polyrand** [comment]
This will be reverted because it adds significant complexity and make new feature development harder to tests.
